In [58]:
df1 = pandas.read_json("supermarkets.json")
df1

ID          Address           City             State Country         Name  \
0   1     3666 21st St  San Francisco          CA 94114     USA      Madeira   
1   2   735 Dolores St  San Francisco          CA 94119     USA  Bready Shop   
2   3      332 Hill St  San Francisco  California 94114     USA  Super River   
3   4     3995 23rd St  San Francisco          CA 94114     USA   Ben's Shop   
4   5  1056 Sanchez St  San Francisco        California     USA      Sanchez   
5   6  551 Alvarado St  San Francisco          CA 94114     USA   Richvalley   

   Employees  
0          8  
1         15  
2         25  
3         10  
4         12  
5         20

In [63]:
df1.loc["332 Hill St", "Country":"ID"]

Series([], Name: 332 Hill St, dtype: object)

In [73]:
list(df1.loc[:,"Name"])

['Madeira',
 'Bready Shop',
 'Super River',
 "Ben's Shop",
 'Sanchez',
 'Richvalley']

In [74]:
df1

ID           City             State Country         Name  \
Address                                                                     
3666 21st St      1  San Francisco          CA 94114     USA      Madeira   
735 Dolores St    2  San Francisco          CA 94119     USA  Bready Shop   
332 Hill St       3  San Francisco  California 94114     USA  Super River   
3995 23rd St      4  San Francisco          CA 94114     USA   Ben's Shop   
1056 Sanchez St   5  San Francisco        California     USA      Sanchez   
551 Alvarado St   6  San Francisco          CA 94114     USA   Richvalley   

                 Employees  
Address                     
3666 21st St             8  
735 Dolores St          15  
332 Hill St             25  
3995 23rd St            10  
1056 Sanchez St         12  
551 Alvarado St         20

In [77]:
df1.iloc[3,1:3]

City     San Francisco
State         CA 94114
Name: 3995 23rd St, dtype: object

In [78]:
df1.drop("City",1)

C:\Users\Clu\AppData\Local\Temp/ipykernel_4268/399123262.py:1: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  df1.drop("City",1)


ID             State Country         Name  Employees
Address                                                              
3666 21st St      1          CA 94114     USA      Madeira          8
735 Dolores St    2          CA 94119     USA  Bready Shop         15
332 Hill St       3  California 94114     USA  Super River         25
3995 23rd St      4          CA 94114     USA   Ben's Shop         10
1056 Sanchez St   5        California     USA      Sanchez         12
551 Alvarado St   6          CA 94114     USA   Richvalley         20

In [79]:
df1.drop("332 Hill St", 0)

C:\Users\Clu\AppData\Local\Temp/ipykernel_4268/2578526509.py:1: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  df1.drop("332 Hill St", 0)


ID           City       State Country         Name  Employees
Address                                                                       
3666 21st St      1  San Francisco    CA 94114     USA      Madeira          8
735 Dolores St    2  San Francisco    CA 94119     USA  Bready Shop         15
3995 23rd St      4  San Francisco    CA 94114     USA   Ben's Shop         10
1056 Sanchez St   5  San Francisco  California     USA      Sanchez         12
551 Alvarado St   6  San Francisco    CA 94114     USA   Richvalley         20

In [80]:
df1

ID           City             State Country         Name  \
Address                                                                     
3666 21st St      1  San Francisco          CA 94114     USA      Madeira   
735 Dolores St    2  San Francisco          CA 94119     USA  Bready Shop   
332 Hill St       3  San Francisco  California 94114     USA  Super River   
3995 23rd St      4  San Francisco          CA 94114     USA   Ben's Shop   
1056 Sanchez St   5  San Francisco        California     USA      Sanchez   
551 Alvarado St   6  San Francisco          CA 94114     USA   Richvalley   

                 Employees  
Address                     
3666 21st St             8  
735 Dolores St          15  
332 Hill St             25  
3995 23rd St            10  
1056 Sanchez St         12  
551 Alvarado St         20

In [81]:
df1.drop(df1.index[0:3],0)

C:\Users\Clu\AppData\Local\Temp/ipykernel_4268/3910286840.py:1: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  df1.drop(df1.index[0:3],0)


ID           City       State Country        Name  Employees
Address                                                                      
3995 23rd St      4  San Francisco    CA 94114     USA  Ben's Shop         10
1056 Sanchez St   5  San Francisco  California     USA     Sanchez         12
551 Alvarado St   6  San Francisco    CA 94114     USA  Richvalley         20

In [83]:
df1.drop(df1.columns[0:3],1)

C:\Users\Clu\AppData\Local\Temp/ipykernel_4268/1887162440.py:1: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only
  df1.drop(df1.columns[0:3],1)


Country         Name  Employees
Address                                        
3666 21st St        USA      Madeira          8
735 Dolores St      USA  Bready Shop         15
332 Hill St         USA  Super River         25
3995 23rd St        USA   Ben's Shop         10
1056 Sanchez St     USA      Sanchez         12
551 Alvarado St     USA   Richvalley         20

In [84]:
df1.columns

Index(['ID', 'City', 'State', 'Country', 'Name', 'Employees'], dtype='object')

In [85]:
df1

ID           City             State Country         Name  \
Address                                                                     
3666 21st St      1  San Francisco          CA 94114     USA      Madeira   
735 Dolores St    2  San Francisco          CA 94119     USA  Bready Shop   
332 Hill St       3  San Francisco  California 94114     USA  Super River   
3995 23rd St      4  San Francisco          CA 94114     USA   Ben's Shop   
1056 Sanchez St   5  San Francisco        California     USA      Sanchez   
551 Alvarado St   6  San Francisco          CA 94114     USA   Richvalley   

                 Employees  
Address                     
3666 21st St             8  
735 Dolores St          15  
332 Hill St             25  
3995 23rd St            10  
1056 Sanchez St         12  
551 Alvarado St         20

In [88]:
len(df1.index)

6

In [90]:
df1["Continent"]=df1.shape[0]*["North America"]
df1

ID           City             State Country         Name  \
Address                                                                     
3666 21st St      1  San Francisco          CA 94114     USA      Madeira   
735 Dolores St    2  San Francisco          CA 94119     USA  Bready Shop   
332 Hill St       3  San Francisco  California 94114     USA  Super River   
3995 23rd St      4  San Francisco          CA 94114     USA   Ben's Shop   
1056 Sanchez St   5  San Francisco        California     USA      Sanchez   
551 Alvarado St   6  San Francisco          CA 94114     USA   Richvalley   

                 Employees      Continent  
Address                                    
3666 21st St             8  North America  
735 Dolores St          15  North America  
332 Hill St             25  North America  
3995 23rd St            10  North America  
1056 Sanchez St         12  North America  
551 Alvarado St         20  North America

In [91]:
df1.shape

(6, 7)

In [94]:
df1["Continent"]=df1["Country"]+","+"North America"
df1

ID           City             State Country         Name  \
Address                                                                     
3666 21st St      1  San Francisco          CA 94114     USA      Madeira   
735 Dolores St    2  San Francisco          CA 94119     USA  Bready Shop   
332 Hill St       3  San Francisco  California 94114     USA  Super River   
3995 23rd St      4  San Francisco          CA 94114     USA   Ben's Shop   
1056 Sanchez St   5  San Francisco        California     USA      Sanchez   
551 Alvarado St   6  San Francisco          CA 94114     USA   Richvalley   

                 Employees          Continent  
Address                                        
3666 21st St             8  USA,North America  
735 Dolores St          15  USA,North America  
332 Hill St             25  USA,North America  
3995 23rd St            10  USA,North America  
1056 Sanchez St         12  USA,North America  
551 Alvarado St         20  USA,North America

In [95]:
df1_t=df1.T
df1_t

Address         3666 21st St     735 Dolores St        332 Hill St  \
ID                         1                  2                  3   
City           San Francisco      San Francisco      San Francisco   
State               CA 94114           CA 94119   California 94114   
Country                  USA                USA                USA   
Name                 Madeira        Bready Shop        Super River   
Employees                  8                 15                 25   
Continent  USA,North America  USA,North America  USA,North America   

Address         3995 23rd St    1056 Sanchez St    551 Alvarado St  
ID                         4                  5                  6  
City           San Francisco      San Francisco      San Francisco  
State               CA 94114         California           CA 94114  
Country                  USA                USA                USA  
Name              Ben's Shop            Sanchez         Richvalley  
Employees                 10                 12                 20  
Continent  USA,North America  USA,North America  USA,North America

In [100]:
df1_t["My Address"]=["7","Iasi", "-","Romania","Clu Andrei", "69","Europe"]
df1_t

Address         3666 21st St     735 Dolores St        332 Hill St  \
ID                         1                  2                  3   
City           San Francisco      San Francisco      San Francisco   
State               CA 94114           CA 94119   California 94114   
Country                  USA                USA                USA   
Name                 Madeira        Bready Shop        Super River   
Employees                  8                 15                 25   
Continent  USA,North America  USA,North America  USA,North America   

Address         3995 23rd St    1056 Sanchez St    551 Alvarado St  My Address  
ID                         4                  5                  6           7  
City           San Francisco      San Francisco      San Francisco        Iasi  
State               CA 94114         California           CA 94114           -  
Country                  USA                USA                USA     Romania  
Name              Ben's Shop            Sanchez         Richvalley  Clu Andrei  
Employees                 10                 12                 20          69  
Continent  USA,North America  USA,North America  USA,North America      Europe

In [101]:
df1=df1_t.T
df1

ID           City             State  Country         Name  \
Address                                                                     
3666 21st St     1  San Francisco          CA 94114      USA      Madeira   
735 Dolores St   2  San Francisco          CA 94119      USA  Bready Shop   
332 Hill St      3  San Francisco  California 94114      USA  Super River   
3995 23rd St     4  San Francisco          CA 94114      USA   Ben's Shop   
1056 Sanchez St  5  San Francisco        California      USA      Sanchez   
551 Alvarado St  6  San Francisco          CA 94114      USA   Richvalley   
My Address       7           Iasi                 -  Romania   Clu Andrei   

                Employees          Continent  
Address                                       
3666 21st St            8  USA,North America  
735 Dolores St         15  USA,North America  
332 Hill St            25  USA,North America  
3995 23rd St           10  USA,North America  
1056 Sanchez St        12  USA,North America  
551 Alvarado St        20  USA,North America  
My Address             69             Europe

In [102]:
type(df1)

pandas.core.frame.DataFrame

In [103]:
import geopy
dir(geopy)

['AlgoliaPlaces',
 'ArcGIS',
 'AzureMaps',
 'BANFrance',
 'Baidu',
 'BaiduV3',
 'Bing',
 'DataBC',
 'GeoNames',
 'GeocodeEarth',
 'Geocodio',
 'Geolake',
 'GoogleV3',
 'Here',
 'HereV7',
 'IGNFrance',
 'LiveAddress',
 'Location',
 'MapBox',
 'MapQuest',
 'MapTiler',
 'Nominatim',
 'OpenCage',
 'OpenMapQuest',
 'Pelias',
 'Photon',
 'PickPoint',
 'Point',
 'Timezone',
 'TomTom',
 'What3Words',
 'What3WordsV3',
 'Yandex',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '__version_info__',
 'adapters',
 'compat',
 'exc',
 'format',
 'geocoders',
 'get_geocoder_for_service',
 'get_version',
 'location',
 'point',
 'timezone',
 'units',
 'util']

In [108]:
from geopy.geocoders import ArcGIS


In [111]:
arc = ArcGIS()


In [115]:
a= arc.geocode("3995 23rd St, San Francisco, CA 94114")

In [116]:
type(a)

geopy.location.Location

In [118]:
a.latitude

37.75292099814533

In [119]:
import pandas
df=pandas.read_csv("supermarkets.csv")
df

ID          Address           City             State Country         Name  \
0   1     3666 21st St  San Francisco          CA 94114     USA      Madeira   
1   2   735 Dolores St  San Francisco          CA 94119     USA  Bready Shop   
2   3      332 Hill St  San Francisco  California 94114     USA  Super River   
3   4     3995 23rd St  San Francisco          CA 94114     USA   Ben's Shop   
4   5  1056 Sanchez St  San Francisco        California     USA      Sanchez   
5   6  551 Alvarado St  San Francisco          CA 94114     USA   Richvalley   

   Employees  
0          8  
1         15  
2         25  
3         10  
4         12  
5         20

In [124]:
df["Address"]=df["Address"]+", "+df["City"]+", "+ df["State"]+ ", " +df["Country"]
df

ID                                            Address           City  \
0   1         3666 21st St, San Francisco, CA 94114, USA  San Francisco   
1   2       735 Dolores St, San Francisco, CA 94119, USA  San Francisco   
2   3  332 Hill St, San Francisco, California 94114, USA  San Francisco   
3   4         3995 23rd St, San Francisco, CA 94114, USA  San Francisco   
4   5    1056 Sanchez St, San Francisco, California, USA  San Francisco   
5   6      551 Alvarado St, San Francisco, CA 94114, USA  San Francisco   

              State Country         Name  Employees  
0          CA 94114     USA      Madeira          8  
1          CA 94119     USA  Bready Shop         15  
2  California 94114     USA  Super River         25  
3          CA 94114     USA   Ben's Shop         10  
4        California     USA      Sanchez         12  
5          CA 94114     USA   Richvalley         20

In [130]:
df["Coordinates"]=df["Address"].apply(arc.geocode)
df

ID                                            Address           City  \
0   1         3666 21st St, San Francisco, CA 94114, USA  San Francisco   
1   2       735 Dolores St, San Francisco, CA 94119, USA  San Francisco   
2   3  332 Hill St, San Francisco, California 94114, USA  San Francisco   
3   4         3995 23rd St, San Francisco, CA 94114, USA  San Francisco   
4   5    1056 Sanchez St, San Francisco, California, USA  San Francisco   
5   6      551 Alvarado St, San Francisco, CA 94114, USA  San Francisco   

              State Country         Name  Employees  \
0          CA 94114     USA      Madeira          8   
1          CA 94119     USA  Bready Shop         15   
2  California 94114     USA  Super River         25   
3          CA 94114     USA   Ben's Shop         10   
4        California     USA      Sanchez         12   
5          CA 94114     USA   Richvalley         20   

                                         Coordinates  
0  (3666 21st St, San Francisco, California, 9411...  
1  (735 Dolores St, San Francisco, California, 94...  
2  (332 Hill St, San Francisco, California, 94114...  
3  (3995 23rd St, San Francisco, California, 9411...  
4  (1056 Sanchez St, San Francisco, California, 9...  
5  (551 Alvarado St, San Francisco, California, 9...

In [133]:
df.Coordinates[0].latitude

37.756632001957215

In [134]:
df

ID                                            Address           City  \
0   1         3666 21st St, San Francisco, CA 94114, USA  San Francisco   
1   2       735 Dolores St, San Francisco, CA 94119, USA  San Francisco   
2   3  332 Hill St, San Francisco, California 94114, USA  San Francisco   
3   4         3995 23rd St, San Francisco, CA 94114, USA  San Francisco   
4   5    1056 Sanchez St, San Francisco, California, USA  San Francisco   
5   6      551 Alvarado St, San Francisco, CA 94114, USA  San Francisco   

              State Country         Name  Employees  \
0          CA 94114     USA      Madeira          8   
1          CA 94119     USA  Bready Shop         15   
2  California 94114     USA  Super River         25   
3          CA 94114     USA   Ben's Shop         10   
4        California     USA      Sanchez         12   
5          CA 94114     USA   Richvalley         20   

                                         Coordinates  
0  (3666 21st St, San Francisco, California, 9411...  
1  (735 Dolores St, San Francisco, California, 94...  
2  (332 Hill St, San Francisco, California, 94114...  
3  (3995 23rd St, San Francisco, California, 9411...  
4  (1056 Sanchez St, San Francisco, California, 9...  
5  (551 Alvarado St, San Francisco, California, 9...

In [139]:
df["Longitude"]=df["Coordinates"].apply(lambda x: x.longitude)
df

ID                                            Address           City  \
0   1         3666 21st St, San Francisco, CA 94114, USA  San Francisco   
1   2       735 Dolores St, San Francisco, CA 94119, USA  San Francisco   
2   3  332 Hill St, San Francisco, California 94114, USA  San Francisco   
3   4         3995 23rd St, San Francisco, CA 94114, USA  San Francisco   
4   5    1056 Sanchez St, San Francisco, California, USA  San Francisco   
5   6      551 Alvarado St, San Francisco, CA 94114, USA  San Francisco   

              State Country         Name  Employees  \
0          CA 94114     USA      Madeira          8   
1          CA 94119     USA  Bready Shop         15   
2  California 94114     USA  Super River         25   
3          CA 94114     USA   Ben's Shop         10   
4        California     USA      Sanchez         12   
5          CA 94114     USA   Richvalley         20   

                                         Coordinates   Latitude   Longitude  
0  (3666 21st St, San Francisco, California, 9411...  37.756632 -122.429411  
1  (735 Dolores St, San Francisco, California, 94...  37.757829 -122.425373  
2  (332 Hill St, San Francisco, California, 94114...  37.755845 -122.428813  
3  (3995 23rd St, San Francisco, California, 9411...  37.752921 -122.431703  
4  (1056 Sanchez St, San Francisco, California, 9...  37.752132 -122.430006  
5  (551 Alvarado St, San Francisco, California, 9...  37.753582 -122.433234

In [1]:
[[123,12,123,12,33],[],[]]

[[123, 12, 123, 12, 33], [], []]

In [2]:
import numpy
n=numpy.arange(27)

In [3]:
n

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [4]:
type(n)

numpy.ndarray

In [5]:
print(n)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26]


In [7]:
n.reshape(3,3,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [8]:
m=numpy.asarray([[123,12,123,12,33],[],[]])

C:\Users\Clu\AppData\Local\Temp/ipykernel_10020/2763146858.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  m=numpy.asarray([[123,12,123,12,33],[],[]])


In [9]:
type(m)

numpy.ndarray

In [10]:
import cv2

In [12]:
im_g=cv2.imread("smallgray.png",1)

print(im_g)

[[[187 187 187]
  [158 158 158]
  [104 104 104]
  [121 121 121]
  [143 143 143]]

 [[198 198 198]
  [125 125 125]
  [255 255 255]
  [255 255 255]
  [147 147 147]]

 [[209 209 209]
  [134 134 134]
  [255 255 255]
  [ 97  97  97]
  [182 182 182]]]


In [13]:
cv2.imwrite("newsmallgray.png",im_g)


True

In [14]:
a=[1,2,3]


In [15]:
a[0:2]

[1, 2]

In [17]:
im_g[0:2,2:4]

array([[[104, 104, 104],
        [121, 121, 121]],

       [[255, 255, 255],
        [255, 255, 255]]], dtype=uint8)

In [18]:
im_g.shape

(3, 5, 3)

In [19]:
im_g[2,4]

array([182, 182, 182], dtype=uint8)

In [21]:
for i in im_g.T:
    print(i)

[[187 198 209]
 [158 125 134]
 [104 255 255]
 [121 255  97]
 [143 147 182]]
[[187 198 209]
 [158 125 134]
 [104 255 255]
 [121 255  97]
 [143 147 182]]
[[187 198 209]
 [158 125 134]
 [104 255 255]
 [121 255  97]
 [143 147 182]]


In [22]:
for i in im_g.flat:
    print (i)

187
187
187
158
158
158
104
104
104
121
121
121
143
143
143
198
198
198
125
125
125
255
255
255
255
255
255
147
147
147
209
209
209
134
134
134
255
255
255
97
97
97
182
182
182


In [23]:
im_g

array([[[187, 187, 187],
        [158, 158, 158],
        [104, 104, 104],
        [121, 121, 121],
        [143, 143, 143]],

       [[198, 198, 198],
        [125, 125, 125],
        [255, 255, 255],
        [255, 255, 255],
        [147, 147, 147]],

       [[209, 209, 209],
        [134, 134, 134],
        [255, 255, 255],
        [ 97,  97,  97],
        [182, 182, 182]]], dtype=uint8)

In [25]:
ims=numpy.hstack((im_g, im_g)) 

In [26]:
ims

array([[[187, 187, 187],
        [158, 158, 158],
        [104, 104, 104],
        [121, 121, 121],
        [143, 143, 143],
        [187, 187, 187],
        [158, 158, 158],
        [104, 104, 104],
        [121, 121, 121],
        [143, 143, 143]],

       [[198, 198, 198],
        [125, 125, 125],
        [255, 255, 255],
        [255, 255, 255],
        [147, 147, 147],
        [198, 198, 198],
        [125, 125, 125],
        [255, 255, 255],
        [255, 255, 255],
        [147, 147, 147]],

       [[209, 209, 209],
        [134, 134, 134],
        [255, 255, 255],
        [ 97,  97,  97],
        [182, 182, 182],
        [209, 209, 209],
        [134, 134, 134],
        [255, 255, 255],
        [ 97,  97,  97],
        [182, 182, 182]]], dtype=uint8)

In [27]:
print(ims)

[[[187 187 187]
  [158 158 158]
  [104 104 104]
  [121 121 121]
  [143 143 143]
  [187 187 187]
  [158 158 158]
  [104 104 104]
  [121 121 121]
  [143 143 143]]

 [[198 198 198]
  [125 125 125]
  [255 255 255]
  [255 255 255]
  [147 147 147]
  [198 198 198]
  [125 125 125]
  [255 255 255]
  [255 255 255]
  [147 147 147]]

 [[209 209 209]
  [134 134 134]
  [255 255 255]
  [ 97  97  97]
  [182 182 182]
  [209 209 209]
  [134 134 134]
  [255 255 255]
  [ 97  97  97]
  [182 182 182]]]


In [28]:
ims=numpy.vstack((im_g,im_g))

In [29]:
ims

array([[[187, 187, 187],
        [158, 158, 158],
        [104, 104, 104],
        [121, 121, 121],
        [143, 143, 143]],

       [[198, 198, 198],
        [125, 125, 125],
        [255, 255, 255],
        [255, 255, 255],
        [147, 147, 147]],

       [[209, 209, 209],
        [134, 134, 134],
        [255, 255, 255],
        [ 97,  97,  97],
        [182, 182, 182]],

       [[187, 187, 187],
        [158, 158, 158],
        [104, 104, 104],
        [121, 121, 121],
        [143, 143, 143]],

       [[198, 198, 198],
        [125, 125, 125],
        [255, 255, 255],
        [255, 255, 255],
        [147, 147, 147]],

       [[209, 209, 209],
        [134, 134, 134],
        [255, 255, 255],
        [ 97,  97,  97],
        [182, 182, 182]]], dtype=uint8)

In [30]:
print(ims)

[[[187 187 187]
  [158 158 158]
  [104 104 104]
  [121 121 121]
  [143 143 143]]

 [[198 198 198]
  [125 125 125]
  [255 255 255]
  [255 255 255]
  [147 147 147]]

 [[209 209 209]
  [134 134 134]
  [255 255 255]
  [ 97  97  97]
  [182 182 182]]

 [[187 187 187]
  [158 158 158]
  [104 104 104]
  [121 121 121]
  [143 143 143]]

 [[198 198 198]
  [125 125 125]
  [255 255 255]
  [255 255 255]
  [147 147 147]]

 [[209 209 209]
  [134 134 134]
  [255 255 255]
  [ 97  97  97]
  [182 182 182]]]


In [36]:
lst=numpy.hsplit(ims,5)

In [38]:
lst

[array([[[187, 187, 187]],
 
        [[198, 198, 198]],
 
        [[209, 209, 209]],
 
        [[187, 187, 187]],
 
        [[198, 198, 198]],
 
        [[209, 209, 209]]], dtype=uint8),
 array([[[158, 158, 158]],
 
        [[125, 125, 125]],
 
        [[134, 134, 134]],
 
        [[158, 158, 158]],
 
        [[125, 125, 125]],
 
        [[134, 134, 134]]], dtype=uint8),
 array([[[104, 104, 104]],
 
        [[255, 255, 255]],
 
        [[255, 255, 255]],
 
        [[104, 104, 104]],
 
        [[255, 255, 255]],
 
        [[255, 255, 255]]], dtype=uint8),
 array([[[121, 121, 121]],
 
        [[255, 255, 255]],
 
        [[ 97,  97,  97]],
 
        [[121, 121, 121]],
 
        [[255, 255, 255]],
 
        [[ 97,  97,  97]]], dtype=uint8),
 array([[[143, 143, 143]],
 
        [[147, 147, 147]],
 
        [[182, 182, 182]],
 
        [[143, 143, 143]],
 
        [[147, 147, 147]],
 
        [[182, 182, 182]]], dtype=uint8)]

In [39]:
lst[0]

array([[[187, 187, 187]],

       [[198, 198, 198]],

       [[209, 209, 209]],

       [[187, 187, 187]],

       [[198, 198, 198]],

       [[209, 209, 209]]], dtype=uint8)